### PR TITLE
Fix bug in handle_rate_limit and take care of proper rounding.

### PR DESCRIPTION
**Pull request by ShrirajHegde**
https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit

According to this document, "retry_after" is the number of seconds in float.

This should prevent getting temporary bans.

Fixes https://github.com/lovvskillz/python-discord-webhook/issues/134

### CODE REVIEW

**Comment by ShrirajHegde** [comment]
Btw, checks are failing due to dependency installation problem in python 3.11 check.

**Comment by lovvskillz** [comment]
Thanks for your fix 👍

**Comment by ShrirajHegde** [comment]
@lovvskillz Btw any plans for parsing `X-RateLimit-Reset` and having a global rate limit?

Because this way of handling rate limit might conflict with threads. That is, multiple threads can keep requesting without being aware of the rate limit. 

Same with async. When await is called, if another task makes a request, it will create a conflict. How about storing `X-RateLimit-Reset` globally whenever it is available and make sure to wait until that time? Thread safety is not a problem race condition is not a serious problem if it occurs 1 or 2 times.

**Comment by lovvskillz** [comment]
@ShrirajHegde Thanks for the hint. I will be thinking about this and implementing it. Sounds good though.

**Comment by ShrirajHegde** [comment]
@lovvskillz Hey, don't forget to publish the current fix to PyPIince the issue is serious.

**Pull request merged**
